version: 2
updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/back"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@joaovictordesousa"
    assignees:
      - "@joaovictordesousa"
    commit-message:
      prefix: "chore(backend)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@joaovictordesousa"
    assignees:
      - "@joaovictordesousa"
    commit-message:
      prefix: "chore(frontend)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/back"
    schedule:
      interval: "monthly"
    reviewers:
      - "@joaovictordesousa"
    assignees:
      - "@joaovictordesousa"
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/front"
    schedule:
      interval: "monthly"
    reviewers:
      - "@joaovictordesousa"
    assignees:
      - "@joaovictordesousa"
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "@joaovictordesousa"
    assignees:
      - "@joaovictordesousa"
    commit-message:
      prefix: "chore(actions)"
    labels:
      - "dependencies"
      - "github-actions"